### PR TITLE
Add contrib list to site

### PR DESCRIPTION
**Pull request by Kukks**

### CODE REVIEW

**Comment by pavlenex** [comment]
Love the idea, however I think it pulls contributors from forks or something. Many of these folks aren't/dependencies really a contributors?
You pull them from the main repo or the organization?
I like the idea of celebrating contributors and featuring them, perhaps @dennisreimann or @dstrukt have a better way to visually present them.



Screenshot 2022-05-11 at 09 39 14

**Comment by Kukks** [comment]
> Love the idea, however I think it pulls contributors from forks or something. Many of these folks aren't/dependencies really a contributors? You pull them from the main repo or the organization? I like the idea of celebrating contributors and featuring them, perhaps @dennisreimann or @dstrukt have a better way to visually present them.
> 
> Screenshot 2022-05-11 at 09 39 14

It goes through all repos under btcpayserver and takes their "contributors" and sorts by contribution count

**Comment by pavlenex** [comment]
Can we exclude certain repos? For example old and stale repos, forks that we no longer use?

**Comment by Kukks** [comment]
Just did that now

**Review by pavlenex — APPROVED** [review]

**Comment by pavlenex** [comment]
@dennisreimann feel free to do a final review and if all good let's merge it, to me it looks good.

**Review by dennisreimann — APPROVED** [review]

**Pull request merged**
