### PR TITLE
Add case studies overview

### PR DESCRIPTION
**Pull request by dennisreimann**
Added a section with teasers and links for the case studies.

grafik

### CODE REVIEW

**Comment by dennisreimann** [comment]
TODO:

- [x] Limit to three: Bitcoin Peole, Bitcopin Jungle, Hodl Hodl
- [x] Link to PDF as well: Add “View Case Study” & “Download PDF” text only button, single line, adequate padding between two CTAs
- [x] Link to View All at the blog

**Comment by dennisreimann** [comment]
Updated according to yesterday's discussion.

**Review by pavlenex — APPROVED** [review]
Looks amazing, thanks for shipping this!

**Comment by mp21-org** [comment]
according to [user feedback](https://t.me/btcpayserver/70021) the translations (german was reported, spanish tested on my end) for the buttons and text around them are missing:

grafik

@dennisreimann

**Pull request merged**
