### PR TITLE
Add SmartStore integration to the integration and plugin section of the website

### LINKED ISSUE #191: Add SmartStore integration to the site
SmartStore integration should be added to the integration section.

Screenshot 2023-12-20 at 18 50 10

https://docs.btcpayserver.org/Smartstore/
```[tasklist]
### Tasks
- [ ] Add smartstore logo
- [ ] Add a link to https://docs.btcpayserver.org/Smartstore/
```

### PR DESCRIPTION
**Pull request by TChukwuleta**
Resolves #191  Add SmartStore integration to the integration and plugin section of the website

Right now I included "smartstore": "SmartStore" to the website.json file, however my guess is that it would need to be added to all the json files in "download/website" folder under transfinex folder, so it displays properly for the different languages

image

### CODE REVIEW

**Comment by pavlenex** [comment]
@TChukwuleta The build is failing, @dennisreimann any idea why?

**Comment by TChukwuleta** [comment]
Yea, @pavlenex  I see it. I think it is trying to load translations and its not seeing it.

**Comment by dennisreimann** [comment]
See my comment here https://github.com/btcpayserver/btcpayserver.org/pull/190#issuecomment-1857399828

**Review by dennisreimann — APPROVED** [review]
tACK. Added the string in Transifex, good to go. 

grafik

**Pull request merged**
