### PR TITLE
Fix mobile menu language switch

### LINKED ISSUE #128: Switching between languages on mobile
When trying to switch between languages the menu "jumps" after clicking on the languages dropdown and automatically clicks on the first language, it is impossible to select the desired language.

## Screen recorder
ezgif-2-168f689c2a37

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes #128. Can you confirm this works, @Zaxounette?

### CODE REVIEW

**Comment by Zaxounette** [comment]
> Can you confirm this works, @Zaxounette?

I'm sorry, I have no idea how to confirm. I have no local dev environnement.

**Comment by dennisreimann** [comment]
@pavlenex Can you verify this locally? If not I'd say let's merge so that both of you can take a look online – at least it won't make things worse :)

**Review by pavlenex — COMMENTED** [review]
Hard to verify this locally, we'd need to merge and test on a mobile. Locally there's no change as the problem does not occur for me on desktop, even when in mobile mode.

**Review by pavlenex — APPROVED** [review]

**Comment by pavlenex** [comment]
I think it's okay now (at least on my end, just tested on mobile) but will let @Zaxounette confirm.

**Pull request merged**
