### PR TITLE
Added Zapier to plugins section

### PR DESCRIPTION
**Pull request by woutersamaey**

### CODE REVIEW

**Comment by woutersamaey** [comment]
Positioning could be better, but it's the best I can do without redoing the whole thing.

Ping @dennisreimann for the layout.

image

**Comment by woutersamaey** [comment]
We need to add the word "zapier" to Transiflex. I tried, but don't think I have permissions for that.

@britttttk or @Zaxounette can you help with this pls?

**Review by dennisreimann — APPROVED** [review]
Improved the alignment a bit and added the translation to Transifex.

**Comment by woutersamaey** [comment]
@dennisreimann Is this auto-deployed to production or how does the site go live?

**Pull request merged**
