### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by vswee**
adds new string `btcpay-server-tag-line`

Once the translations are acceptable on transifex, the marker can change to use the new string id

### CODE REVIEW

**Comment by pavlenex** [comment]
@vswee Awesome, what's needed on Transifex end? I believe this string has been translated already, can we retrieve it?

**Comment by vswee** [comment]
@pavlenex https://github.com/btcpayserver/btcpayserver.org/tree/vswee-add-legacy-source-files/source/legacy/en-json has the old translations for reference. Feel free to delete that branch if we don't need it past this instance.

**Comment by pavlenex** [comment]
@vswee I am just trying to understand things before I delete stuff (learned my lesson 😆)

So this PR #119 adds a new string. Then we have #120 which we will merge once we update translations of the earlier string on Transifex? Just trying to understand the workflow needed on my end. Mhm, so actually this string is already on transifex. I though we wiped it.

**Comment by vswee** [comment]
@pavlenex This PR:

- adds the new string while maintaining the old one.
- is deliberately discrete from PR #120 to allow time to get the strings translated to, (is it 100% since last consensus?) the desired level before attempting to build pages with it.

The `vswee-add-legacy-source-files` branch is just to share one of the latest transifex translations bundles from before the big `id` change.

Merging #119 now will allow transifex to pick up the new string within a few hours.
@dennisreimann might need to confirm that there are no conditions in the build method that might break this, just to be sure.

**Comment by pavlenex** [comment]
Perfect, thanks for clarifying that. That's what I though, just wanted to be 100% sure. I think that string is actually translated 100% for the languages we have, since we never deleted it.

string

So there shouldn't be any breaking changes or missing translations.

**Review by RiccardoMasutti — APPROVED** [review]

**Review by pavlenex — APPROVED** [review]

**Pull request merged**
