### PR TITLE
Change vid thumbnail + add new video

### PR DESCRIPTION
**Pull request by ghost**
Addresses #150 and #151.

### CODE REVIEW

**Review by Zaxounette — COMMENTED** [review]
The {{what-is-btcpay}} & {{btcpay-for-communities}} titles are rendered as is.

chrome_nkzhXFww0X

**Comment by ghost** [comment]
I think this is a build issue related to Transifex.

**Review by dennisreimann — APPROVED** [review]
I've added the Translations to the Transifex master and did some minor style improvements.

Looks good!

**Comment by ghost** [comment]
@dennisreimann For future reference, what is the workflow for updating the Transifex master? I wasn't able to find much information on that.

**Comment by dennisreimann** [comment]
AFAIK it can only be done via the Transifex web interface. We change the `source/transifex-master/en.json` as you did and then upload the new version on Transifex. Afterwards you can `npm run init` to pull the new translation files. (You will need [the `TRANSIFEX_TOKEN`](https://github.com/btcpayserver/btcpayserver.org#how-to-build) as an environment variable for that to work)

**Comment by ghost** [comment]
@dennisreimann ,  the translations worked for me locally after you updated the Transifex master, but after I pulled your git changes to the website they are no longer resolving correctly (i.e. the titles display as  {{what-is-btcpay}} & {{btcpay-for-communities}}, as before)

**Comment by dennisreimann** [comment]
You are correct, it looks like someone reuploaded the master file from the master branch.

@pavlenex @britttttk Or is there another way they might have disappeared?

**Comment by pavlenex** [comment]
Nothing on my end. What do you guys need to check this? Ping @britttttk she should be able to assist with this.

**Comment by dennisreimann** [comment]
I've reuploaded the en.json master file from this branch. 

Imho we can merge this-- anything missing?

**Pull request merged**
