### PR TITLE
Add space between Store and Point of Sale buttons

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Just a little graphical fix:

btcpay website fix

### CODE REVIEW

**Review by vswee — CHANGES_REQUESTED** [review]
Great PR again but it needs to be applied to the `temple.html` file under `source`/`html`. Likewise for the donation page template if you're feeling up it it ;) Cheers @RiccardoMasutti

**Comment by RiccardoMasutti** [comment]
> Great PR again but it needs to be applied to the `temple.html` file under `source`/`html`. Likewise for the donation page template if you're feeling up it it ;) Cheers @RiccardoMasutti

Ok, let me edit :+1:

**Comment by RiccardoMasutti** [comment]
@vswee ready

**Review by vswee — COMMENTED** [review]
`&nbsp;`

**Comment by pavlenex** [comment]
It seems like @vswee committed and fixed this. Hence the conflicts, I'll go ahead and close the issue and pull request. Don't let this discourage you, your PR's are more than welcome, feel free to DM if you'd like to continue contributing.

**Pull request closed without merging**
