### PR TITLE
Include nopcommerce to plugin and integration section

### LINKED ISSUE #200: Add nopCommerce integration on the website
Just like we did for SmartStore in https://github.com/btcpayserver/btcpayserver.org/pull/194 we should now add nopCommerce icon and link to the integration https://www.nopcommerce.com/en/btcpay-server-accept-bitcoin-payments

I wanted to add a link to docs instead, but I think directly linking to a marketplace is more appropriate since it has better call to actions to download plugin followed by good description.

### PR DESCRIPTION
**Pull request by TChukwuleta**
Resolves #200  by including nopcommerce to the plugin and integration section

### CODE REVIEW

**Comment by pavlenex** [comment]
@TChukwuleta Could you please also include GrandNode, it was just released today. https://grandnode.com/btcpay-server-accept-bitcoin-payments ? 🙏 


We're pumping integrations 🔥 

Don't know why the build is failing? cc @dennisreimann is it because of the translation?

**Comment by dennisreimann** [comment]
Yes, all builds that don't run in the context of the main repo (this one has the base on @TChukwuleta) won't pass, because the Transifex token isn't available.

**Comment by pavlenex** [comment]
Alright, we can ignore them then, all good.

**Comment by TChukwuleta** [comment]
sure @pavlenex  I would do so

**Comment by TChukwuleta** [comment]
Hey @pavlenex I have included it. 
@dennisreimann  Kindly review.

 Thank you

**Comment by pavlenex** [comment]
Thanks @TChukwuleta I wasn't able to build it locally either don't think your PR is an issue but there's something with our build and local setups that needs to be fixed or made easier, even with Transifex token, I'm unable to build locally, I'll leave it to @dennisreimann to give final look and merge.

```
> btcpayserver.org@1.0.0 init /Users/p/Downloads/untitled folder/btcpayserver.org
> npm-run-all clean -p d:*


> btcpayserver.org@1.0.0 clean /Users/p/Downloads/untitled folder/btcpayserver.org
> rimraf dist && mkdir -p dist


> btcpayserver.org@1.0.0 d:translations /Users/p/Downloads/untitled folder/btcpayserver.org
> node -r dotenv/config tasks/download_translations.js && cp transifex/resources/video.json transifex/download/video/en_GB.json && cp transifex/resources/website.json transifex/download/website/en_GB.json


> btcpayserver.org@1.0.0 d:contributors /Users/p/Downloads/untitled folder/btcpayserver.org
> node -r dotenv/config tasks/download_contributors.js

(node:3364) UnhandledPromiseRejectionWarning: TypeError: this.auth is not a function
    at s.request (/Users/p/Downloads/untitled folder/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:302410)
    at Nn.fetch (/Users/p/Downloads/untitled folder/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:299423)
    at Nn.get (/Users/p/Downloads/untitled folder/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:300907)
    at Function.get (/Users/p/Downloads/untitled folder/btcpayserver.org/node_modules/@transifex/api/dist/node.transifexApi.js:1:293841)
    at /Users/p/Downloads/untitled folder/btcpayserver.org/tasks/download_translations.js:14:56
    at Object.<anonymous> (/Users/p/Downloads/untitled folder/btcpayserver.org/tasks/download_translations.js:53:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
cp: transifex/download/video/en_GB.json: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btcpayserver.org@1.0.0 d:translations: `node -r dotenv/config tasks/download_translations.js && cp transifex/resources/video.json transifex/download/video/en_GB.json && cp transifex/resources/website.json transifex/download/website/en_GB.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 d:translations script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/p/.npm/_logs/2024-03-03T09_05_31_222Z-debug.log
ERROR: "d:translations" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btcpayserver.org@1.0.0 init: `npm-run-all clean -p d:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btcpayserver.org@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by dennisreimann** [comment]
It is the Transifex token not being available. Shall we simply integrate it in the repo for everyone to be available? This is annoying.

**Comment by pavlenex** [comment]
Are there any security implications with it? I would say we should make it as easy as possible (netlify previews included) for people to test changes locally. If there are no security implications we can add token otherwise we could simply exclude transifex locally or have an additional way for people testing translations, wdyt @dennisreimann any other options?

I did add a token but somehow it didn't work for me 😞

**Pull request merged**
