### PR TITLE
Remove 'Altcoin' Support

### PR DESCRIPTION
**Pull request by 6102bitcoin**
Remove reference to 'Altcoins' (Scams)

### CODE REVIEW

**Comment by ernestgracia** [comment]
Remove ‘Altcoints’

**Comment by FrancisPouliot** [comment]
Ack. No need to give them any exposure. If people want to reuse the code for their shitcoin, they'll figure it out.

**Comment by rockstardev** [comment]
Listen, if any of you wants to discuss this in serious manner - let's do that when we meet at some conference.

But in a nutshell - I started working on BtcPayServer because I believe in freedom and choice. It's not up to BitPay to dictate Segwit2X to merchants. The same way - it's not up to me to dictate whether people should use an altcoin. Whether I believe in freedom of choice is not shown when there is something I agree with; it's shown when there is something I disagree with.

So, I'll close this issue and ask all 3 of you - if you want to help us with BtcPayServer - let us find more productive avenue. I would prefer we use our energy for something better... OK?

**Comment by FrancisPouliot** [comment]
What is not serious about this discussion? 

You have the freedom to choose to promote shitcoins.

**Comment by pavlenex** [comment]
Removing an entire section would be withholding information from user. 

The section says:
`Opt in integrations for several altcoins maintained by Altcoins community.` 
imo, that's very important piece of information.

The only reason the list of altcoins should be removed is for UX reasons, because it looks a bit weird and maybe should be in-line. Why nobody is discussing that?

NACK. I do not want to withhold information from the user. Removing information in which way altcoins are supported is important. Removing this from the website will not remove the ability for people to opt in for altcoins.

You're turning this into narrative "BTCPay refused  to remove altcoins" and that's really sad. Go ahead, get your likes and RTs, when the party is over come back and let's discuss how we can seriously improve the experience for people using website. I am opened that we adjust the list of coins itself, but not withhold information to fit somebody's narrative.

**Comment by FrancisPouliot** [comment]
It's not a narrative. You are supporting altcoins, and altcoins are using BTCPay to promote their altcoins, and when Bitcoiners redirect people to BTCPAYserver they see a list of all the altcoins supported, which gives promotions to these altcoins.

I am not against you wasting your time to integrate altcoins, I am agaisnt you promoting the adoption of altcoins.

**Comment by pavlenex** [comment]
Altcoins are not supported out of the box, like many external services, they are an opt in thing. To add an altcoin user needs to have a certain level of technical knowledge. Altcoins are integrated and maintained by their communities. We've been through this 200 times.

Removing the section on the website will not delete the fact people can opt in for external services. In my opinion it's important to emphasize that and I am against of removing such information.

We can discuss a list, but only because it's a poor UX imo, not because it will make BTCPay look less good or bad in the face of maximalists minimalists shitcoinalist or whichever group.

**Comment by rockstardev** [comment]
Well, pretty much everything so far is "not serious". I would even start from assumption that those lines @6102bitcoin removed can be labeled as "promotion of shitcoins". To me there is zero "promotion" there... it's just piece of information.

If our end goal is to reduce scams and "guide people" toward solid parts of this frenzied ecosystem we all participate in - removing those few lines, to me, is like a drop in the ocean. Worse for that goal yet - I actually think this thread and everything you @6102bitcoin and @FrancisPouliot started on Twitter will end up producing net positive "promotion" of altcoins.

What makes me sad is that - I am 100% behind BITCOIN FIRST... ESPECIALLY for new people. That's why I'm insisting on "seriousness"... we just can't take a lofty goal and try to reach it with poor effort.

**Comment by FrancisPouliot** [comment]
The way I see it, if I support BTCPay publicly and invite people to go there, I am exposing myself to recommending a service who explicitely states it supports altcoins, and lists the altcoins.

Secondly, you are now "curators" of which altcoins you support. What is the criteria?

Thridly, if you say you do not support altcoins, why is it such a prominent feature of the readme?

If feel like you are trying to make a point of not removing altcoins, I don't know why. Possibly you want to dissassociate yourselves from maximalists, which is fine. But remember that Bitcoin maximalists such as myself were the ones that promoted BTCPay server the most. They are your main users and contributors.

**Comment by FrancisPouliot** [comment]
@rockstardev I assure you I am 100% serious. If you don't take this seriously, that is your prerogative. I don't judge you, I am trying to optimize my own experience in promoting BTCPay server.

**Comment by rockstardev** [comment]
My comment on "seriousness" was relating to action suggested by this pull request and discussion by this point: https://github.com/btcpayserver/btcpayserver.github.io/pull/27#issuecomment-473397724

I only saw additional comments you and @pavlenex posted after I clicked Comment.

Which makes me think whether I should continue discussing my POV at this point or let you two first finish.

I don't doubt your personal seriousness... discussion between you and me on how to prevent noobs falling for scams is long overdue.

**Comment by FrancisPouliot** [comment]
> discussion between you and me on how to prevent noobs for falling for scams is long overdue.

Step 1: don't support scams in the software you create.
Step 2: if you do, don't advertise it.
Step 3: if someone else supports scams, publicly call them out.

I think you understimate the influece that simply listing altcoins can have, particularly on a high-profile project like BTCPay. "If these well-know and respecte Bitcoin developpers support altcoins, surely they can't be that bad, right?"

Also: Dogecoin is a fucking scam.

**Comment by pavlenex** [comment]
@FrancisPouliot  I agree about the readme. It probably should be more evident, that one is on me. I will open a PR in the main repo to make it more evident.

My whole point is - removing information from the website will make zero effect, making sure it's 100% correct and communicated properly, will have the effect.

I think we're now trying to fit way too many things into a single PR. 

In future, certainly we can discuss in separate issues:
1. How will BTCPay handle altcoins, are they bottleneck to the system or a security risk
2. How to communicate them to users and alt developers
3. Should there be separate branches

It's a sensitive topic, but we're now trying to comment on bunch of things when in fact this single PR is about website. 

Back to the PR, wouldn't removing information from the website be dishonest and hypocritical, when users can still opt in and integrate whatever coin they support. I think it's much broader issue that has to be discussed. 

I hope we can have constructive discussions on this and many other topics, and not just when there's a Twitter war going and when there are likes and RT's to be collected.

**Comment by 6102bitcoin** [comment]
Has this thread gone off topic? Yes
Where is the best place to have this discussion or are you never going to change you minds?
Is this about likes and rt's? No, I am speaking for myself but I couldn't care less about those.

@rockstardev are you seriously suggesting that @FrancisPouliot and myself are supporting shitcoins by suggesting that they are removed from BTCPayServer while simultaneously saying that you think that the main page of the project lists "Altcoin Integration" as a feature?

**Comment by hadnet** [comment]
Since when supporting scams has something to do with freedom of choice? Is choosing to not to promote scams a freedom of choice for BTCPayServer too?

**Comment by rockstardev** [comment]
@6102bitcoin if others won't interrupt us, I guess this place could be good as any to discuss between you and me. Maybe IRL would be better... because if our goal is to come to consensus - we have a lot of ground to cover... and it's question of whether you and me have enough energy to invest in this discussion.

For what you are trying to do, from my POV the main question is philosophical: whether it is really possible to retain "purity" and prevent "decay"? My whole life I've been trying to believe in possibility of that outcome... but practice disproved me at every step.

Also, one thing that I've noticed: in case you want to destroy something - you better be sure you have enough energy to do it. Because if you don't, then insufficient energy you invest in destruction will get multiplied and compounded -> effectively increasing the energy already present in what you are trying to destroy.

That's the context in which I was mentioning you and Francis... you are obviously not supporting shitcoins (please don't strawman me too much if we are to have discussion)... but by taking non-calculated actions - you are giving energy to them and effectively "promoting" them. What has all this discussion been so far... if not one big promotion of individual stances on shitcoins and their usage?

**Comment by rockstardev** [comment]
And just to note - on this discussion - I will be directly responding only to @6102bitcoin.

You @FrancisPouliot - we'll talk when we meet IRL... if you want to talk before than, let's organize call and talk about concrete stuff.

Everyone else - feel free to join https://chat.btcpayserver.org and we can talk there.

**Comment by 6102bitcoin** [comment]
Hi Rockstardev, 

Thanks for taking the time to write that reply - I do think that we are mostly on the same page.

My gut feeling, from what I have observed on twitter, in interviews and through second hand information is that most of the key contributors to BTCPayServer are, themselves, bitcoin-only. By that I mean that they hold only bitcoin and are not interested in holding other 'altcoins'. With that in mind I have been surprised to see the slow creep of explicit integration of 'altcoins' into BTCPayServer. 

I **fully support any individual to act in the manner which they deem fit**, and if the collective opinion of the BTCPayServer contributors is that having 'altcoin integration' is something that you support then so be it. 

**I** do not support 'altcoin' integration as I view these 'altcoins' as scams and a distraction (particularly for new merchants who will flood to BTCPayServer in the next bull run). I wish to promote bitcoin-only tools, products and services in order to help accelerate the transition to a fairer world - with this in mind, I aim to express my distaste in the direction that BTCPayServer is heading with regard to 'altcoin' integration, and invite others who feel the same way (but who have been silent thus far) to join me in making our opinion known in case there is a possibility that key contributors to BTCPayServer feel the same way. 

My hope is/was that a snowball effect would result in the revelation that actually, the inclusion of 'altcoin integration' is seen as a key failing bay a large quorum of your peers, including other BTCPayServer contributors. I hope/hoped that should the sentiment shift, the project would change tack and invite 'altcoins' to fork the project to integrate 'altcoins' **leaving BTCPayServer to focus on BTC**. 

I appreciate that my approach has been haphazard, any my use of twitter has been aggravating and not conducive to discussion, and for that I am sorry.

**Comment by rockstardev** [comment]
Well, I'm glad that we will discuss details here. We do share goal of preventing scams from happening... but we differ in our understanding of situation and paths we are taking toward achieving the end goal.

I personally would like nothing more than to witness "Bitcoin only" world. But, I don't think that's achievable. The whole "Bitcoin only" - block/destroy everyone else - is futile approach taken by those who do not want to witness developing complexity and are aiming for "simple" solution.

And all this I'm talking about is older than Bitcoin... it's wider process embedded in universe. Let's say it was possible for you and me to go back in time and kill Vitalik before he creates ultimate platform for spawning shitcoins - Ethereum. We somehow perfectly execute the mission. Our young, "brilliant" boy philosopher that promises moon and stars (while delivering flaky science project without market cap) is dead. But is our mission success? Of course no... and it's even worse - now Justin Sun and Bytemaster have more freedom to do their own terrible things.

In life it's very rare that you are given clear cut choice between - good and bad. Most of the time it's choice between bad, terrible, worse and deadly. And you NEED to choose between those... or time will run out and you'll fuck everything up even more.

What I would especially advise you is to take caution on setting goals where you need to influence others through "destruction for their own good". You better be sure that you are doing the right thing... and destroying something that deserves destruction. Because if you are wrong or you don't have clear goal and ability to achieve it... you are:

a) participating in destruction of something that's actually good... making you bad
b) as I explained in my previous post - you could be supercharging something terrible through your inadequate actions
c) destroying something that is not good... but not bad either... all while other terrible things grew larger

Unfortunately there is d, e, f... and whole alphabet of sorrow. Which is why I always recommend to people - don't destroy, but rather create your own thing. Don't stop others from talking and try to influence them... build what you like and focus on talking about that.

And if you are not able to create own thing - do not destroy - but join those who are building something you like and follow their lead. Focus on building beyond the level of destruction... make what you are working on so pretty and great that it's obvious people should use it; without army of sales people or conflict that markets your solution.

Only by doing that can you actually do some long-term good... and help reduce damage new generation of Travons will inflict upon people during next bull market. Simplistic solutions - deleting this paragraph or that, declaring "Bitcoin only, everything else is scam" - that's bringing a toothpick to a gun fight... and is more about saving yourself than saving others.

**Comment by ALeschinsky** [comment]
What a great discussion!

I'll just leave my 2 sats: I agree with everything @6102bitcoin said above.

I wish BTCPay luck! :)

**Comment by 6102bitcoin** [comment]
Interesting perspective, I will take some time and think about what you have said. Thanks for taking the time to explain your reasoning.

**Pull request closed without merging**
