### PR TITLE
Add dennisreimann to donation list

### PR DESCRIPTION
**Pull request by dennisreimann**
Thanks @pavlenex for the invite! 🙏

### CODE REVIEW

**Comment by pavlenex** [comment]
Dennis has been a great and consistent contributor. He also contributed to docs repository.

ACK.

**Comment by Kukks** [comment]
Ack

**Comment by pavlenex** [comment]
@vswee can you please push these changes live?

**Comment by dennisreimann** [comment]
> @vswee can you please push these changes live?

Have you though about automating the deployment so that fresh commits on master build the changes and deploy a new version of the website (via GitHub Actions)? I do this with several of my static sites and could help setting it up.

**Comment by Kukks** [comment]
@dennisreimann #71

**Pull request merged**
