### PR TITLE
blog and directory link added to index.html

### PR DESCRIPTION
**Pull request by drkjc**
First time committing to an open source. Let me know if I'm way off base here.

### CODE REVIEW

**Review by Kukks — CHANGES_REQUESTED** [review]
Thanks for the contrib!

Correct me if I'm wrong @vswee but the files you edited are actually generated automatically from https://github.com/btcpayserver/btcpayserver.github.io/blob/master/source/template.html

So you would need to do the change there.

**Comment by vswee** [comment]
> Correct me if I'm wrong @vswee but the files you edited are actually generated automatically from https://github.com/btcpayserver/btcpayserver.github.io/blob/master/source/template.html

Ideally, yes. At the moment however, building the site uses a local template.
Nevertheless, wherever a PR is made (on a translated language index.html or the source template file) all the [translated subdirectory] indexes will have to get pulled so effectively, you can do PRs wherever you're comfortable.

**Comment by drkjc** [comment]
Good to know. Thanks!

**Comment by pavlenex** [comment]
Can you resolve the conflicts?

**Pull request closed without merging**
